MagicBoxShop/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;

namespace MagicBoxShop.Controllers
{
    public class ShoppingCart
    {
        PresentsEntities presentsDB = new PresentsEntities();

        string ShoppingCartId { get; set; }

        public const string CartSessionKey = "CartId";

        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }

        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        public void AddToCart(Product product, int count)
        {
            var cartItem =
                 presentsDB.Carts.SingleOrDefault(c => c.CartId == ShoppingCartId && c.ProductId == product.ProductId);
            if (cartItem == null)
            {
                cartItem = new Cart
                {
                    ProductId = product.ProductId,
                    CartId = ShoppingCartId,
                    Count = count,
                    DateCreated = DateTime.Now
                };

                presentsDB.Carts.Add(cartItem);
            }
            else
            {
               cartItem.Count+=count;
            }
            presentsDB.SaveChanges();
        }

        public int RemoveFromCart(int id)
        {
            var cartItem = presentsDB.Carts.Single(cart => cart.CartId == ShoppingCartId && cart.RecordId == id);
            int itemCount = 0;
            if (cartItem != null)
            {
               presentsDB.Carts.Remove(cartItem);
               presentsDB.SaveChanges();
            }
            return itemCount;
        }

        public void EmptyCart()
        {
            var cartItems = presentsDB.Carts.Where(cart => cart.CartId == ShoppingCartId);
            foreach (var cartItem in cartItems)
            {
                presentsDB.Carts.Remove(cartItem);
            }
            presentsDB.SaveChanges();
        }

        public List<Cart> GetCartItems()
        {
            return presentsDB.Carts.Where(cart => cart.CartId == ShoppingCartId).ToList();
        }

        public int GetCount()
        {
            int? count = (from cartItems in presentsDB.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            return count ?? 0;
        }

        public decimal GetTotal()
        {
            decimal? total = (from cartItems in presentsDB.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count * cartItems.Product.Price).Sum();
            return total ?? decimal.Zero;
        }

        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;
            var cartItems = GetCartItems();
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    Order = order,
                    UnitPrice = item.Product.Price,
                    Quantity = item.Count,
                    Product = item.Product
                };
                orderTotal += (item.Count * item.Product.Price);
                presentsDB.OrderDetails.Add(orderDetail);
            }
            order.Total = orderTotal;
            presentsDB.SaveChanges();
            EmptyCart();
            return order.OrderId;
        }

        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] = context.User.Identity.Name;
                }
                else
                {
                    Guid tempCartId = Guid.NewGuid();
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        public void MigrateCart(string userName)
        {
            var shoppingCart = presentsDB.Carts.Where(c => c.CartId == ShoppingCartId);
            foreach (Cart item in shoppingCart)
            {
                item.CartId = userName;
            }
            presentsDB.SaveChanges();
        }

        public int ChangeCart(int id, int count)
        {
            var cartItem = presentsDB.Carts.Single(cart => cart.CartId == ShoppingCartId && cart.RecordId == id);
            if (cartItem != null)
            {
                cartItem.Count = count;
                presentsDB.SaveChanges();
            }
            return count;
        }
    }
}

MagicBoxShop/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MagicBoxShop.Models;

namespace MagicBoxShop.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

MagicBoxShop/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;

namespace MagicBoxShop.Controllers
{
    public class CheckoutController : Controller
    {
        PresentsEntities presentsDB = new PresentsEntities();
       
        public ActionResult AddressAndPayment()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("LogOn", "Account");
            }
            var cart = ShoppingCart.GetCart(this.HttpContext);
            Session["total"] = cart.GetTotal().ToString();
            return View();
        }
        

        
        [HttpPost]
        public ActionResult AddressAndPayment(Order model)
        {
            if (ModelState.IsValid)
            {
                if (User.Identity.IsAuthenticated)
                {
                    var order = new Order();
                    TryUpdateModel(order);

                    order.Username = User.Identity.Name;
                    order.OrderDate = DateTime.Now;
                    order.Status = "Необработанный";
                    order.OrderDetails = new List<OrderDetail>();
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.CreateOrder(order);

                    return RedirectToAction("Complete",
                                            new {id = order.OrderId});

                }
                else return RedirectToAction("LogOn", "Account");
            }
           return View(model);

        }

        public ActionResult Complete(int id)
        {
           bool isValid = presentsDB.Orders.Any(
                o => o.OrderId == id &&
                o.Username == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }

    }
}

MagicBoxShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;
using MagicBoxShop.ViewModels;

namespace MagicBoxShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        PresentsEntities presentsDB = new PresentsEntities();
       
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);
        }

        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            string productName = presentsDB.Carts
                .Single(item => item.RecordId == id).Product.Name;
            int itemCount = cart.RemoveFromCart(id);
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " был удален с корзины.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results, JsonRequestBehavior.AllowGet);
         }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

        public ActionResult  ChengeQuontityCart(int id, int q)
       {
           var cart = ShoppingCart.GetCart(this.HttpContext);
           int itemCount = cart.ChangeCart(id, q);
           var results = new ShoppingCartChangeViewModel()
           {
               CartTotal = cart.GetTotal(),
               CartCount = cart.GetCount(),
               ItemCount = itemCount,
               ChangeId = id
          };
           return Json(results, JsonRequestBehavior.AllowGet);
       }
    }
}

MagicBoxShop/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;

namespace MagicBoxShop.Controllers
{
    public class StoreController : Controller
    {
        PresentsEntities presentsDB = new PresentsEntities();

        public ActionResult Index()
        {
            var events = presentsDB.Subcategories.ToList();
            return View(events);
        }

        public ActionResult Browse(int id, bool isCategory, int page = 1, int itemPerPage = 10, int sort = 0)
        {
            
            ViewBag.categoryId = id;
            ViewBag.sort = sort;
            ViewBag.IsCategory = isCategory;
            List<Product> products = new List<Product>();
            if (isCategory)
            {
                var categoryName = presentsDB.Categories.FirstOrDefault(e => e.CategoryId == id).Name;
                ViewBag.categoryName = categoryName;               
                Category category = presentsDB.Categories.Find(id);
                foreach (var sub in category.Subcategories)
                {
                    products.AddRange(sub.Products);
                }
            }
            else
            {
                var categoryName = presentsDB.Subcategories.FirstOrDefault(e => e.SubcategoryId == id).Name;
                ViewBag.categoryName = categoryName;             
                products = presentsDB.Subcategories.Find(id).Products.ToList();
            }
            products = products.Distinct().ToList();
            products = products.Where(e => e.IsValid).ToList();

            if (sort == 0)
            {
                products = products.OrderBy(x => x.Price).ToList();
            }
            else if (sort == 1)
            {
                products = products.OrderByDescending(x => x.Price).ToList();
            }
            var data = new PageableData<Product>(products, page, itemPerPage);
            return View(data);
        }

        [HttpPost]
        public ActionResult Details(int id, int count)
        {
            var addedProduct = presentsDB.Products.Single(pr => pr.ProductId == id);
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedProduct, count);
            return RedirectToAction("Details");
        }

        public ActionResult Details(int id)
        {
            var product = presentsDB.Products.Find(id);
            DirectoryInfo d = new DirectoryInfo(Server.MapPath(product.ArtUrl));
            List<string> fileList = new List<string>();
            foreach (FileInfo f in d.GetFiles("*.jpg"))
            {
                fileList.Add(Path.Combine(product.ArtUrl, f.Name));
            }
            ViewBag.ListImg = fileList;
            return View(product);
        }

       public ActionResult Menu()
        {
            var categories = presentsDB.Categories.ToList();

            return PartialView(categories);
        }
    }
}

MagicBoxShop/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Корзина (" + ViewData["CartCount"] + ")",
    "Index",
    "ShoppingCart",
    new { id = "cart-status" })

MagicBoxShop/Views/ShoppingCart/Index.cshtml
@model MagicBoxShop.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Корзина";
}
<script src="/Scripts/jquery-1.5.1.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id"); 
            //alert(123);
            if (recordToDelete != '') {

                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }

                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Корзина (' + data.CartCount + ')');
                    },"json");
            }
        });
        $(".ChengeQuontityLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {

                // Perform the ajax post
                $.post("/ShoppingCart/ChengeQuontityCart", { "id": recordToDelete, "q" : $('#count').val() },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        $('#cart-total').text(data.CartTotal);
                        $('#cart-status').text('Корзина (' + data.CartCount + ')');
                    }, "json");
            }
        });

    });


    function handleUpdate() {
        // Load and deserialize the returned JSON data
        var json = context.get_data();
        var data = Sys.Serialization.JavaScriptSerializer.deserialize(json);

        // Update the page elements
        if (data.ItemCount == 0) {
            $('#row-' + data.DeleteId).fadeOut('slow');
        } else {
            $('#item-count-' + data.DeleteId).text(data.ItemCount);
        }

        $('#cart-total').text(data.CartTotal);
        $('#update-message').text(data.Message);
        $('#cart-status').text('Cart (' + data.CartCount + ')');
    }
</script>
<h3>
    <em>Список товаров</em> в корзине:
</h3>
@if(Model.CartItems.Count > 0)
{
    <p class="button">
     @Html.ActionLink("Подтвердить >>", "AddressAndPayment", "Checkout")
    </p>

<div id="update-message">
</div>
    <table>
        <tr>
            <th>
                Название продука
            </th>
            <th>
                Цена
            </th>
            <th>
                Количество
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.CartItems)
        {
            <tr id="row-@item.RecordId">
                <td>
                    @Html.ActionLink(item.Product.Name, "Details", "Store", new { id = item.ProductId }, new {@class = "mp-back"})
                </td>
                <td>
                    @item.Product.Price
                </td>
                <td id="item-count-@item.RecordId">
                    <div>
                        <input type="number" name="count" id ="count" value="@item.Count" size="3" min="1" max="@item.Product.Quantity" class="ChengeQuontityLink" data-id="@item.RecordId"/>
                    </div>
                </td>
                <td>
                    <a href="#" class="RemoveLink" data-id="@item.RecordId">Удалить</a>
                </td>
            </tr>
        }
        <tr>
            <td>
                Общая сумма
            </td>
            <td>
            </td>
            <td>
            </td>
            <td id="cart-total">
                @Model.CartTotal
            </td>
        </tr>
    </table>
}
else
{
    <em>Ваша корзина пока пуста. Пора что-то менять.</em>
}