MagicBoxShop/Models/Subcategory.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;


namespace MagicBoxShop.Models
{
    [Bind(Exclude = "SubcategoryId")]
    public class Subcategory
    {
        [ScaffoldColumn(false)]
        public int SubcategoryId { get; set; }

        [DisplayName("Название подкатегории")]
        [Required(ErrorMessage = "Обязательное поле")]
        [RegularExpression(@"[A-Za-zА-Яа-я0-9,:._()\s\""]+",
       ErrorMessage = "Название может содержать только буквы, цифры, нижнее подчеркивание и знаки препинания.")]
        public string Name { get; set; }

        [DisplayName("Характеризирующий вопрос")]
        [RegularExpression(@"[A-Za-zА-Яа-я0-9,:.\?_()\s\""]+",
       ErrorMessage = "Вопрос может содержать только буквы, цифры, нижнее подчеркивание и знаки препинания.")]
        public string Question { get; set; }

        [DisplayName("Родительская категория")]
        public virtual Category RootCategory { get; set; }

        public virtual List<Product> Products { get; set; } 
    }
}

MagicBoxShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;

namespace MagicBoxShop.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private PresentsEntities db = new PresentsEntities();

        public ActionResult Index()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(db.Categories.ToList());
        }

        public ActionResult Details(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        public ActionResult Create()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory sub = new Subcategory();
            sub.Name = "Разное";
            sub.Products = new List<Product>();
            sub.Question = "";
            sub.RootCategory = category;
            if (ModelState.IsValid)
            {
                
                db.Categories.Add(category);
                db.Subcategories.Add(sub);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        public ActionResult Edit(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (category.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту категорию нельзя редактировать");
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Category category)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category categoryOld = db.Categories.Find(id);
            category.CategoryId = id;
            if (ModelState.IsValid)
            {
                db.Entry(categoryOld).State = EntityState.Modified;
                db.Entry(categoryOld).CurrentValues.SetValues(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public ActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (category.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту категорию нельзя удалять");
                return RedirectToAction("Index");
            }
            return View(category);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            Category reserv = db.Categories.First(e => e.Name == "Разное");
            reserv.Subcategories.AddRange(category.Subcategories);
            foreach (var sub in category.Subcategories)
            {
                sub.RootCategory = reserv;
                if(sub.Name.Equals("Разное"))
                {
                    sub.Name = category.Name;
                }
            }
            db.Categories.Remove(category);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MagicBoxShop/Controllers/SubcategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;
using System.Windows;

namespace MagicBoxShop.Controllers
{
  //  [Authorize(Roles = "Admin")]
    public class SubcategoryController : Controller
    {
        private PresentsEntities db = new PresentsEntities();

        public ActionResult Index()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(db.Subcategories.ToList());
        }

        public ActionResult IndexСoncrete(int categoryId)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(db.Subcategories.Where(e=> e.RootCategory.CategoryId == categoryId).ToList());
        }

        public ActionResult Details(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory subcategory = db.Subcategories.Find(id);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            return View(subcategory);
        }

        public ActionResult Create()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Session["categoryListForCreate"] = db.Categories.ToList();
            return View();
        }

        public ActionResult Concrete(int categoryId)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category cc = db.Categories.Find(categoryId);
            Session["categoryListForCreate"] = new List<Category>() { cc };
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Subcategory subcategory)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category cc = db.Categories.Find(Convert.ToInt32(Request["chooseCategory"]));
            subcategory.RootCategory = cc;
            subcategory.Products = new List<Product>();
            if (ModelState.IsValid)
            {
                cc.Subcategories.Add(subcategory);
                db.Subcategories.Add(subcategory);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
           return View();
        }

        public ActionResult Edit(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory subcategory = db.Subcategories.Find(id);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            if (subcategory.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту подкатегорию нельзя редактировать");
                return RedirectToAction("Index");
            }

            Session["categoryListForCreate"] = db.Categories.ToList();
            return View(subcategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Subcategory subcategoryEdited)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory subcategoryOld = db.Subcategories.Find(id);
            subcategoryEdited.SubcategoryId = id;
            int CategoryId = Convert.ToInt32(Request["InRootCategory"]);
            if(CategoryId != subcategoryOld.RootCategory.CategoryId)
            {
                Category cc = db.Categories.Find(CategoryId);
                subcategoryOld.RootCategory.Subcategories.Remove(subcategoryOld);
                subcategoryEdited.RootCategory = cc;
                cc.Subcategories.Add(subcategoryEdited);
            }else
            {
                subcategoryEdited.RootCategory = subcategoryOld.RootCategory;
            }
            subcategoryEdited.Products= subcategoryOld.Products;
            if(ModelState.IsValid)
            {
                db.Entry(subcategoryOld).CurrentValues.SetValues(subcategoryEdited);

                if (subcategoryOld.RootCategory==null || subcategoryOld.RootCategory.CategoryId != CategoryId)
                {
                    subcategoryOld.RootCategory = subcategoryEdited.RootCategory;
                    db.Subcategories.Remove(subcategoryEdited);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(subcategoryEdited);
        }

        public ActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory subcategory = db.Subcategories.Find(id);
            
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            if (subcategory.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту подкатегорию нельзя удалять");
                return RedirectToAction("Index");
            }
            return View(subcategory);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory subcategory = db.Subcategories.Find(id);

            Subcategory reserv = db.Subcategories.First(e => e.Name == "Разное" && e.RootCategory.CategoryId == subcategory.RootCategory.CategoryId);//  (e => e.Name == "Разное");
            reserv.Products.AddRange(subcategory.Products);

            foreach (var product in subcategory.Products)
            {
                product.Subcategories.Remove(subcategory);
                product.Subcategories.Add(reserv);
            }
            db.Subcategories.Remove(subcategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MagicBoxShop/Views/Subcategory/Concrete.cshtml
@model MagicBoxShop.Models.Subcategory

@{
    ViewBag.Title = "Создать";
}

<h2>Создание новой подкатегории</h2>

@using (Html.BeginForm("Create", "Subcategory", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>
           <div class="editor-label">
            @Html.LabelFor(model => model.Question)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Question)
            @Html.ValidationMessageFor(model => model.Question)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.RootCategory)
        </div>
        <div class="editor-field">
            <select name="chooseCategory">
                @foreach (var c in (List<MagicBoxShop.Models.Category>)Session["categoryListForCreate"])
                {
                    <option value="@c.CategoryId" >@c.Name </option>
                }
            </select>
        </div>

        <p>
            <input type="submit" value="Готово" />
        </p>
}

<div>
    @Html.ActionLink("Назад", "Index", new {} , new {@class = "mp-back"})
</div>

MagicBoxShop/Views/Subcategory/Create.cshtml
@model MagicBoxShop.Models.Subcategory

@{
    ViewBag.Title = "Создать";
}

<h2>Создание новой подкатегории</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>
           <div class="editor-label">
            @Html.LabelFor(model => model.Question)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Question)
            @Html.ValidationMessageFor(model => model.Question)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.RootCategory)
        </div>
        <div class="editor-field">
            <select name="chooseCategory">
                @foreach (var c in (List<MagicBoxShop.Models.Category>)Session["categoryListForCreate"])
                {
                    <option value="@c.CategoryId" >@c.Name </option>
                }
            </select>
        </div>

        <p>
            <input type="submit" value="Готово" />
        </p>
}

<div>
    @Html.ActionLink("Назад", "Index", new {}, new {@class = "mp-back"})
</div>

MagicBoxShop/Views/Subcategory/Delete.cshtml
@model MagicBoxShop.Models.Subcategory

@{
    ViewBag.Title = "Удалить";
}

<h2>Удаление подкатегории</h2>

<p>Вы уверены, что хотите удалить 
    <strong>@Model.Name</strong>?
</p>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Удалить" />
    </p>
}
<p> @Html.ActionLink("Назад", "Index", new {}, new {@class = "mp-back"})</p>

MagicBoxShop/Views/Subcategory/Details.cshtml
@model MagicBoxShop.Models.Subcategory

@{
    ViewBag.Title = "Подробно";
}

<h2>Подробнее</h2>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name):
    </div>
<div class="display-field">
    @Html.DisplayFor(model => model.Name)
</div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Question):
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Question)
    </div>
    
    <div class="display-label">
         @Html.DisplayNameFor(model => model.RootCategory):
    </div>
    <div class="display-field">
         <a href="@Url.Action("Details", "Category", new { id = Model.RootCategory.CategoryId })" class="mp-back"> @Html.DisplayFor(model => model.RootCategory.Name)</a>
    </div>
     <div class="display-label">
         Содержит товаров:
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Products.Count)
        @Html.ActionLink("Просмотреть", "IndexConcrete", "StoreManager", new {id = Model.SubcategoryId, isCategory = false}, new {@class = "mp-back"})
    </div>
<p>
     @if (!Model.Name.Equals("Разное"))
    {
        @Html.ActionLink("Редактировать", "Edit", new { id=Model.SubcategoryId }, new {@class = "mp-back"}) <b>|</b>
    }
    @Html.ActionLink("Назад", "Index", new {}, new {@class = "mp-back"})
</p>

MagicBoxShop/Views/Subcategory/Edit.cshtml
@model MagicBoxShop.Models.Subcategory

@{
    ViewBag.Title = "Рдеактирование";
}

<h2>Редактирование подкатегории</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>
       <div class="editor-label">
            @Html.LabelFor(model => model.Question)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Question)
            @Html.ValidationMessageFor(model => model.Question)
        </div>
         <div class="editor-label">
           Родительская категория
        </div>
        <div class="editor-field">
            <select name="InRootCategory" >
                @foreach (var c in (List<MagicBoxShop.Models.Category>)Session["categoryListForCreate"])
                {
                    if(c.CategoryId == Model.RootCategory.CategoryId)
                    {
                        <option selected value="@c.CategoryId" >@c.Name </option>
                    }else
                    {
                        <option value="@c.CategoryId" >@c.Name </option>
                    }
                    
                }
            </select>
        </div>

        <p>
            <input type="submit" value="Сохранить" />
        </p>
}

<div>
    <p>
    @Html.ActionLink("Назад", "Index", new {}, new {@class = "mp-back"})
    </p>
</div>

MagicBoxShop/Views/Subcategory/Index.cshtml
@model IEnumerable<MagicBoxShop.Models.Subcategory>

@{
    ViewBag.Title = "Подкатегории";
}

<h2>Подкатегории</h2>

<p>
    @Html.ActionLink("Создать подкатегорию", "Create", new {}, new {@class = "mp-back"})
</p>
@if(Model.Count()>0)
{
    <table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RootCategory)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(model => item.RootCategory.Name)
        </td>
        <td>
            @if (!item.Name.Equals("Разное"))
            {
                @Html.ActionLink("Редактировать", "Edit", new { id=item.SubcategoryId }, new {@class = "mp-back"}) <b>|</b>
                @Html.ActionLink("Подробнее", "Details", new { id=item.SubcategoryId }, new {@class = "mp-back"}) <b>|</b>
                @Html.ActionLink("Удалить", "Delete", new { id=item.SubcategoryId }, new {@class = "mp-back"})
            }else
            {
                 @Html.ActionLink("Подробнее", "Details", new { id=item.SubcategoryId }, new {@class = "mp-back"})
            }
            
        </td>
    </tr>
}

</table>
    
} 
else
{
    <em>Список подкатегорий пуст</em>
}



MagicBoxShop/Views/Subcategory/Indexæoncrete.cshtml
@model IEnumerable<MagicBoxShop.Models.Subcategory>

@{
    ViewBag.Title = "Подкатегории";
}

<h2>Подкатегории</h2>
@if(Model.Count()>0)
{
      @Html.ActionLink("Создать подкатегорию", "Concrete", "Subcategory", new {categoryId = Model.First().RootCategory.CategoryId}, new {@class = "mp-back"})
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RootCategory)
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => item.RootCategory.Name)
                </td>
                <td>
                    @if (!item.Name.Equals("Разное"))
                    {
                        @Html.ActionLink("Редактировать", "Edit", new { id=item.SubcategoryId }, new {@class = "mp-back"}) <b>|</b>
                        @Html.ActionLink("Подробнее", "Details", new { id=item.SubcategoryId }, new {@class = "mp-back"}) <b>|</b>
                        @Html.ActionLink("Удалить", "Delete", new { id=item.SubcategoryId }, new {@class = "mp-back"})
                    }else
                    {
                         @Html.ActionLink("Подробнее", "Details", new { id=item.SubcategoryId }, new {@class = "mp-back"})
                    }
            
                </td>
            </tr>
        }

        </table>
}else
{
    <em>Список подкатегорий пуст</em>
}
