MagicBoxShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;

namespace MagicBoxShop.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private PresentsEntities db = new PresentsEntities();

        public ActionResult Index()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(db.Categories.ToList());
        }

        public ActionResult Details(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        public ActionResult Create()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory sub = new Subcategory();
            sub.Name = "Разное";
            sub.Products = new List<Product>();
            sub.Question = "";
            sub.RootCategory = category;
            if (ModelState.IsValid)
            {
                
                db.Categories.Add(category);
                db.Subcategories.Add(sub);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        public ActionResult Edit(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (category.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту категорию нельзя редактировать");
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Category category)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category categoryOld = db.Categories.Find(id);
            category.CategoryId = id;
            if (ModelState.IsValid)
            {
                db.Entry(categoryOld).State = EntityState.Modified;
                db.Entry(categoryOld).CurrentValues.SetValues(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public ActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (category.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту категорию нельзя удалять");
                return RedirectToAction("Index");
            }
            return View(category);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            Category reserv = db.Categories.First(e => e.Name == "Разное");
            reserv.Subcategories.AddRange(category.Subcategories);
            foreach (var sub in category.Subcategories)
            {
                sub.RootCategory = reserv;
                if(sub.Name.Equals("Разное"))
                {
                    sub.Name = category.Name;
                }
            }
            db.Categories.Remove(category);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MagicBoxShop/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;
using System.Data;
using System.Data.Entity;
using System.IO;

namespace MagicBoxShop.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class StoreManagerController : Controller
    {
        private const String ImagePath = "/Content/Images";
        private const String DefaultImagePath = "/Content/Images/Default";
        private PresentsEntities presentsDB = new PresentsEntities();

        public ActionResult Index(int id = -1, bool isCategory = false, int page = 1, int itemPerPage = 10, int sort = 0 )
        {
            ViewBag.sort = sort;
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }          
            var products = new List<Product>();
            var notOrderList = presentsDB.Products.Where(e => e.IsValid == true).ToList();
            switch (sort)
            {
                case 0: products = notOrderList.OrderBy(e => e.Name).ToList();
                    break;
                case 1: products = notOrderList.OrderByDescending(e => e.Name).ToList();
                    break;
                case 2: products = notOrderList.OrderBy(e => e.Price).ToList();
                    break;
                case 3: products = notOrderList.OrderByDescending(e => e.Price).ToList();
                    break;
                case 4: products = notOrderList.OrderBy(e => e.Quantity).ToList();
                    break;
                case 5: products = notOrderList.OrderByDescending(e => e.Quantity).ToList();
                    break;
                case 6: products = notOrderList.OrderBy(e => e.Popularity).ToList();
                    break;
                case 7: products = notOrderList.OrderByDescending(e => e.Popularity).ToList();
                    break;
                default: products = notOrderList;
                    break;
            }
            var data = new PageableData<Product>(products.ToList(), page, itemPerPage);
            return View(data);
        }

        public ActionResult IndexConcrete(int id, bool isCategory, int page = 1, int itemPerPage = 10, int sort = 0)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            ViewBag.IsCategory = isCategory;
            ViewBag.categoryId = id;
            ViewBag.sort = sort;
            List<Product> notOrderList = new List<Product>();
            if (isCategory)
            {
                var categoryName = presentsDB.Categories.FirstOrDefault(e => e.CategoryId == id).Name;
                ViewBag.categoryName = categoryName;
                Category category = presentsDB.Categories.Find(id);
                foreach (var sub in category.Subcategories)
                {
                    notOrderList.AddRange(sub.Products);
                }
            }
            else
            {
                var categoryName = presentsDB.Subcategories.FirstOrDefault(e => e.SubcategoryId == id).Name;
                ViewBag.categoryName = categoryName;
                notOrderList = presentsDB.Subcategories.Find(id).Products.ToList();
            }
            notOrderList = notOrderList.Distinct().ToList();
            notOrderList = notOrderList.Where(e => e.IsValid).ToList();
            switch (sort)
            {
                case 0: notOrderList = notOrderList.OrderBy(e => e.Name).ToList();
                    break;
                case 1: notOrderList = notOrderList.OrderByDescending(e => e.Name).ToList();
                    break;
                case 2: notOrderList = notOrderList.OrderBy(e => e.Price).ToList();
                    break;
                case 3: notOrderList = notOrderList.OrderByDescending(e => e.Price).ToList();
                    break;
                case 4: notOrderList = notOrderList.OrderBy(e => e.Quantity).ToList();
                    break;
                case 5: notOrderList = notOrderList.OrderByDescending(e => e.Quantity).ToList();
                    break;
                case 6: notOrderList = notOrderList.OrderBy(e => e.Popularity).ToList();
                    break;
                case 7: notOrderList = notOrderList.OrderByDescending(e => e.Popularity).ToList();
                    break;
                default: notOrderList = notOrderList;
                    break;
            }
            var data = new PageableData<Product>(notOrderList, page, itemPerPage);
            return View(data);
        }

        public ActionResult Details(int id)
        {
            var product = presentsDB.Products.Find(id);
            DirectoryInfo d = new DirectoryInfo(Server.MapPath(product.ArtUrl));
            List<string> fileList = new List<string>();
            foreach (FileInfo f in d.GetFiles("*.jpg"))
            {
                fileList.Add(Path.Combine(product.ArtUrl, f.Name));
            }
            ViewBag.ListImg = fileList;
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(product);
        }


        public ActionResult Create()
        {
            Session["categoryList"] = presentsDB.Categories.ToList();
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View();
        }

        private void getLocation(Product pr)
        {
            if(pr.Subcategories == null)
            {
                pr.Subcategories = new List<Subcategory>();
            }
            else
            {
                List<Subcategory> sub = pr.Subcategories;
                foreach (var subcategory in sub)
                {
                    subcategory.Products.Remove(pr);
                }
                pr.Subcategories.Clear();
            }
    

            List<string> tags = (List<string>)Session["ListOfTags"];
            if (tags != null)
            {
                foreach (var tag in tags)
                {
                    if (Request[tag] == "on")
                    {
                        int id = Convert.ToInt32(tag.Substring(2));
                        Subcategory sc = presentsDB.Subcategories.Find(id);
                        pr.Subcategories.Add(sc);
                        sc.Products.Add(pr);
                    }
                }
            }
            if(pr.Subcategories.Count == 0)
            {
                Subcategory subcategory = presentsDB.Subcategories.First(e => e.Name.Equals("Разное") && e.RootCategory.Name.Equals("Разное"));
                pr.Subcategories.Add(subcategory);
                subcategory.Products.Add(pr);
            }
        }


        private bool loadAndSave(List<HttpPostedFileBase> uploadFile, string uniqueFolder)
        {
            bool flag = true;
            foreach (HttpPostedFileBase file in uploadFile)
            {
                if (file != null && file.ContentLength > 0)
                {
                    TimeSpan span = DateTime.Now.Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc));
                    String uniqueName = Path.Combine(uniqueFolder, span.TotalMilliseconds.ToString() + ".jpg");
                    file.SaveAs(uniqueName);
                    flag = false;
                }
            }
            return flag;
        }

        private string plaseArts (List<HttpPostedFileBase> uploadFile)
        {
            string filePath = "";
            bool flag = true;
            if (uploadFile != null && uploadFile.Count > 0)
            {
                TimeSpan span = DateTime.Now.Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc));
                String uniqueFolder = Path.Combine(Server.MapPath(ImagePath), span.TotalSeconds.ToString());
                filePath = Path.Combine(ImagePath, span.TotalSeconds.ToString());
                DirectoryInfo d = new DirectoryInfo(uniqueFolder);
                d.Create();
                flag = loadAndSave(uploadFile, uniqueFolder);
            }

            if (flag)
            {
                filePath = DefaultImagePath;
            }
            filePath = filePath.Replace('\\', '/');
            return filePath;
        }

        [HttpPost]
        public ActionResult Create(Product pr, List<HttpPostedFileBase> uploadFile )
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            pr.ArtUrl = plaseArts(uploadFile);

            pr.DateCreated = DateTime.Now;
            pr.Popularity = 0;
            pr.IsValid = true;

            getLocation(pr);
            

            if (ModelState.IsValid)
            {
                presentsDB.Products.Add(pr);
                presentsDB.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pr);
        }

        public ActionResult Edit(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Product pr = presentsDB.Products.Find(id);
            Session["categoryList"] = presentsDB.Categories.ToList();
            return View(pr);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Product productNew, List<HttpPostedFileBase> uploadFile)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            var productOld = presentsDB.Products.First(e => e.ProductId==id);
            //productNew.ProductId = id;
            getLocation(productOld);

MagicBoxShop/Views/StoreManager/Create.cshtml
@model MagicBoxShop.Models.Product
@{
    ViewBag.Title = "Добавить";
}

<h2>Создание подарка</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/HelpfullFunctions.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "StoreManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name, "Название")
        </div>                

        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        
        <div class="editor-label">
            Положение в каталоге:
        </div>
        <div class="editor-field">
            @{ List<string> listN = new List<string>(); }
            @foreach (var c in (List<MagicBoxShop.Models.Category>)Session["categoryList"])
            {
                if (c.Subcategories.Count > 0)
                {
                    <fieldset>
                        <legend>@c.Name</legend>
                        @foreach (var sc in c.Subcategories){
                            <p><input type="checkbox" name="s @sc.SubcategoryId">@sc.Name</p>
                            listN.Add("s " + @sc.SubcategoryId);
                        }
                    </fieldset>
                }
                Session.Add("ListOfTags", listN);
            }
           </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Price, "Цена")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
        
         <div class="editor-label">
            @Html.LabelFor(model => model.Description, "Описание")
        </div>

        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { style = "width:300px ;height:100px" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Quantity, "Количество")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>
        <div class="editor-field">
            <table id="images"  class = "testTable">	
				<tr>		
					<td colspan="2" ><input type="button" name="Button1" value="Добавить изображение" onclick="onPush()" class="m-btn" align="left"></td>
				</tr>				
			</table>
        </div>
        <input type="submit" value="Готово" />
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

MagicBoxShop/Views/StoreManager/Delete.cshtml
@model MagicBoxShop.Models.Product

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление товара</h2>

<p>Вы уверены, что хотите удалить 
   <strong>@Model.Name</strong>?
</p>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Удалить" />
    </p>
    <p>
        @Html.ActionLink("Назад", "Index", new {}, new {@class = "mp-back"})
    </p>

}

MagicBoxShop/Views/StoreManager/Details.cshtml
@model MagicBoxShop.Models.Product

@{
    ViewBag.Title = "Подробно";
}

<h2>Информация о подарке</h2>

    <div class="display-label">Название</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Цена</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>
    
    <div class="display-label">Количество</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>
    <div class="display-label">Продано единиц товара</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Popularity)
    </div>
    <div class="display-label">Описание</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Description)
</div>

    <div class="display-label">Расположение в меню</div>
<div class="display-field">
    @if(Model.Subcategories.Count >0){
        foreach (var sub in  Model.Subcategories)
        {
            <a href="@Url.Action("Details", "Category", new { id = sub.RootCategory.CategoryId})"> @sub.RootCategory.Name</a> <b>></b> <a href="@Url.Action("Details", "Subcategory", new { id = sub.SubcategoryId })"> @sub.Name</a><br>
        }
    }


</div>


<div class="display-label">В магазине в продаже с </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>


    <div class="display-label">Изображения</div>
    <div class="display-field">
         @foreach (var img in ViewBag.ListImg)
         {
            
             <p>
                  
                 <img alt="@Model.Name" src="@img"  height="200"/>    
             </p>
             
         }

    </div>
<div class="det-href">
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id=Model.ProductId }, new {@class = "mp-back"}) |
    @Html.ActionLink("Назад", "Index", new {}, new {@class = "mp-back"})
</p>
    </div>

MagicBoxShop/Views/StoreManager/Edit.cshtml
@model MagicBoxShop.Models.Product

@{
    ViewBag.Title = "Изменение";
}

<h2>Редактирование подарка</h2>

<script src="@Url.Content("~/Scripts/HelpfullFunctions.js")" type="text/javascript"></script>

@using (Html.BeginForm("Edit", "StoreManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
         <div class="editor-label">
            Положение в каталоге:
        </div>
        <div class="editor-field">
            @{ List<string> listN = new List<string>(); }
            @foreach (var c in (List<MagicBoxShop.Models.Category>)Session["categoryList"])
            {
                if (c.Subcategories.Count > 0)
                {
                    <fieldset>
                        <legend>@c.Name</legend>
                        @foreach (var sc in c.Subcategories){
                            if(Model.Subcategories.Contains(sc))
                            {
                                <p><input type="checkbox" checked name="s @sc.SubcategoryId">@sc.Name</p>
                            }
                            else
                            {
                                <p><input type="checkbox" name="s @sc.SubcategoryId">@sc.Name</p>
                            }
                            listN.Add("s " + @sc.SubcategoryId);
                        }
                    </fieldset>
                }
                Session.Add("ListOfTags", listN);
            }
           </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Quantity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.ArtUrl)
        </div>

        <div class="editor-field">
            <table id="images"  class = "testTable">                	
                <tr>		
                    <td colspan="2" ><input type="button" name="Button1" value="Добавить изображение" onclick="onPush()" class="m-btn"></td>
                </tr>				
            </table>
        </div>
    <p>
        <input type="submit" value="Сохранить" />
    </p>
    
}
<div>
    @Html.ActionLink("Назад", "Index", new {}, new {@class = "mp-back"})
</div>

MagicBoxShop/Views/StoreManager/Index.cshtml
@using MagicBoxShop
@model MagicBoxShop.Models.PageableData<MagicBoxShop.Models.Product>

@helper Truncate(string input, int length)
{
    if (input.Length <= length) {
        @input
    } else {
        @input.Substring(0, length)<text>...</text>
    }
}

@{
    ViewBag.Title = "Информация про товары";
}

<script src="@Url.Content("~/Content/modern-buttons/js/jquery-1.8.0.min.js")" 
           type="text/javascript"></script>
<script src="@Url.Content("~/Content/modern-buttons/js/m-dropdown.min.js")"
        type="text/javascript"></script>

<h2>Каталог товаров</h2>

<p>
    @Html.ActionLink("Добавить товар", "Create", new {}, new {@class="mp-back"})
</p> 
<div class="album-head">
       <div align="right" background="red">
            На странице:
            <div class="m-btn-group">
                <a class="m-btn dropdown-toggle mini" data-toggle="dropdown" href="#">
                    @Model.ItemPerPage <span class="caret"></span>
                </a>
                <ul class="m-dropdown-menu">
                    <li><a href="@Url.Action("Index", new {page = 1, itemPerPage = 5, sort = @ViewBag.sort})" >5</a></li>
                    <li><a href="@Url.Action("Index", new {page = 1, itemPerPage = 10, sort = @ViewBag.sort})" >10</a></li>
                    <li><a href="@Url.Action("Index", new {page = 1, itemPerPage = 20, sort = @ViewBag.sort})" >20</a></li>
                    <li><a href="@Url.Action("Index", new {page = 1, itemPerPage = 50, sort = @ViewBag.sort})" >50</a></li>
                    <li><a href="@Url.Action("Index", new {page = 1, itemPerPage = 100, sort = @ViewBag.sort})" >100</a></li>
                </ul>
                @Html.PageLinks(Model.PageNo, Model.CountPage, x => Url.Action("Index", new {page = x, itemPerPage = Model.ItemPerPage, sort = @ViewBag.sort}))
            </div>
         </div>
    </div>
<table>
   <tr>
        <th>
            Название <br />
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 0})" class ="admsort"><i class="m-icon-swapup"></i></a>
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 1})" class ="admsort"><i class="m-icon-swapdown"></i></a>
        </th>
        <th>
            Количество <br />
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 4})" class ="admsort"><i class="m-icon-swapup"></i></a>
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 5})" class ="admsort"><i class="m-icon-swapdown"></i></a>
        </th>
        <th>
            Цена <br />
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 2})" class ="admsort"><i class="m-icon-swapup"></i></a>
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 3})" class ="admsort"><i class="m-icon-swapdown"></i></a>
        </th>
        <th>
            Продано единиц <br />
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 6})" class ="admsort"><i class="m-icon-swapup"></i></a>
            <a href="@Url.Action("Index", new {page = 1, itemPerPage = @Model.ItemPerPage, sort = 7})" class ="admsort"><i class="m-icon-swapdown"></i></a>
        </th>
        <th>
            Описание
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.List) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Popularity)
            </td>
            <td>
                @Truncate(item.Description, 25)
            </td>

            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id=item.ProductId }, new {@class="mp-back"}) |
                @Html.ActionLink("Подробно", "Details", new { id=item.ProductId }, new {@class="mp-back"}) |
                @Html.ActionLink("Удалить", "Delete", new { id=item.ProductId }, new {@class="mp-back"})
            </td>
        </tr>
    }

</table>

<div class="m-btn-group">
        @Html.PageLinks(Model.PageNo, Model.CountPage, x => Url.Action("Index", new {page = x, itemPerPage = Model.ItemPerPage, sort = @ViewBag.sort}))
</div>