MagicBoxShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;

namespace MagicBoxShop.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private PresentsEntities db = new PresentsEntities();

        public ActionResult Index()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(db.Categories.ToList());
        }

        public ActionResult Details(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        public ActionResult Create()
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Subcategory sub = new Subcategory();
            sub.Name = "Разное";
            sub.Products = new List<Product>();
            sub.Question = "";
            sub.RootCategory = category;
            if (ModelState.IsValid)
            {
                
                db.Categories.Add(category);
                db.Subcategories.Add(sub);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        public ActionResult Edit(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (category.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту категорию нельзя редактировать");
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Category category)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category categoryOld = db.Categories.Find(id);
            category.CategoryId = id;
            if (ModelState.IsValid)
            {
                db.Entry(categoryOld).State = EntityState.Modified;
                db.Entry(categoryOld).CurrentValues.SetValues(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public ActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (category.Name.Equals("Разное"))
            {
                System.Windows.Forms.MessageBox.Show("Эту категорию нельзя удалять");
                return RedirectToAction("Index");
            }
            return View(category);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Category category = db.Categories.Find(id);
            Category reserv = db.Categories.First(e => e.Name == "Разное");
            reserv.Subcategories.AddRange(category.Subcategories);
            foreach (var sub in category.Subcategories)
            {
                sub.RootCategory = reserv;
                if(sub.Name.Equals("Разное"))
                {
                    sub.Name = category.Name;
                }
            }
            db.Categories.Remove(category);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MagicBoxShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;
using System.Windows.Forms;

namespace MagicBoxShop.Controllers
{
    public class OrderController : Controller
    {
        private PresentsEntities db = new PresentsEntities();

         // [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(db.Orders.ToList().OrderByDescending(e => e.OrderDate));
        }

         // [Authorize(Roles = "Admin")]
        public ActionResult IndexConrete(string status)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            ViewBag.Status = status;
            return View(db.Orders.Where(e=> e.Status.Equals(status)).ToList().OrderBy(e => e.OrderDate));

        }

       // [Authorize(Roles = "Admin")]
        public ActionResult Details(int id = 0)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

       // [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            if (order.Status.Equals("Выполненный") || order.Status.Equals("Отменен"))
            {
                MessageBox.Show("Это состаяние является конечным. Его нельзя изменить.", "Невозможно изменить");
                return RedirectToAction("Index");
            }
            var types = new List<string>() { "Необработанный", "Обработанный", "Выполненный", "Отменен" };
            ViewBag.StatusList = types;
            return View(order);
        }

       // [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order ordern, int id )
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Order order = db.Orders.Find(id);
           
            string eS = order.Status;
            order.Status = Request["statusNew"];
            if (order.Status.Equals("Выполненный") && !eS.Equals(order.Status))
            {
                foreach (var od in order.OrderDetails)
                {
                    if (od.Product.Quantity - od.Quantity < 0)
                    {
                       MessageBox.Show("Для выполнения заказа на складе не хватает " + od.Product.Name + ". Необходимо еще " + (od.Quantity - od.Product.Quantity) + " экземпляров", "Не достаточно товара");
                       return RedirectToAction("IndexConrete", new { status = eS });
                    }

                }
                foreach(var od in order.OrderDetails)
                {

                        od.Product.Quantity -= od.Quantity;
                        od.Product.Popularity += od.Quantity;

                }
            }
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("IndexConrete", new {status = eS});
        }

      
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

      //  [Authorize(Roles = "User")]
        public ActionResult PersonalOrders(){
            if (!User.IsInRole("User"))
            {
                return HttpNotFound();
            }
            List<Order> orders = db.Orders.Where(e => e.Username == User.Identity.Name).ToList();

            return View(orders.OrderByDescending(e => e.OrderDate));
        }
    }
}

MagicBoxShop/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicBoxShop.Models;

namespace MagicBoxShop.Controllers
{
    public class StoreController : Controller
    {
        PresentsEntities presentsDB = new PresentsEntities();

        public ActionResult Index()
        {
            var events = presentsDB.Subcategories.ToList();
            return View(events);
        }

        public ActionResult Browse(int id, bool isCategory, int page = 1, int itemPerPage = 10, int sort = 0)
        {
            
            ViewBag.categoryId = id;
            ViewBag.sort = sort;
            ViewBag.IsCategory = isCategory;
            List<Product> products = new List<Product>();
            if (isCategory)
            {
                var categoryName = presentsDB.Categories.FirstOrDefault(e => e.CategoryId == id).Name;
                ViewBag.categoryName = categoryName;               
                Category category = presentsDB.Categories.Find(id);
                foreach (var sub in category.Subcategories)
                {
                    products.AddRange(sub.Products);
                }
            }
            else
            {
                var categoryName = presentsDB.Subcategories.FirstOrDefault(e => e.SubcategoryId == id).Name;
                ViewBag.categoryName = categoryName;             
                products = presentsDB.Subcategories.Find(id).Products.ToList();
            }
            products = products.Distinct().ToList();
            products = products.Where(e => e.IsValid).ToList();

            if (sort == 0)
            {
                products = products.OrderBy(x => x.Price).ToList();
            }
            else if (sort == 1)
            {
                products = products.OrderByDescending(x => x.Price).ToList();
            }
            var data = new PageableData<Product>(products, page, itemPerPage);
            return View(data);
        }

        [HttpPost]
        public ActionResult Details(int id, int count)
        {
            var addedProduct = presentsDB.Products.Single(pr => pr.ProductId == id);
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedProduct, count);
            return RedirectToAction("Details");
        }

        public ActionResult Details(int id)
        {
            var product = presentsDB.Products.Find(id);
            DirectoryInfo d = new DirectoryInfo(Server.MapPath(product.ArtUrl));
            List<string> fileList = new List<string>();
            foreach (FileInfo f in d.GetFiles("*.jpg"))
            {
                fileList.Add(Path.Combine(product.ArtUrl, f.Name));
            }
            ViewBag.ListImg = fileList;
            return View(product);
        }

       public ActionResult Menu()
        {
            var categories = presentsDB.Categories.ToList();

            return PartialView(categories);
        }
    }
}

MagicBoxShop/Views/Store/Browse.cshtml
@using MagicBoxShop

@model MagicBoxShop.Models.PageableData<MagicBoxShop.Models.Product>
@{
    ViewBag.Title = "Список подарков";
}

<script src="@Url.Content("~/Content/modern-buttons/js/jquery-1.8.0.min.js")" 
           type="text/javascript"></script>
 <script src="@Url.Content("~/Content/modern-buttons/js/m-dropdown.min.js")"
    type="text/javascript"></script>

<div>
    <div class="album-head">
        <h2> @ViewBag.categoryName </h2>
        <div class="sort-head">
            Сортировать по цене
            <a href="@Url.Action("Browse", "Store", new { id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory, page = 1, itemPerPage = @Model.ItemPerPage, sort = 0})"><i class="m-icon-swapup"></i></a>
            <a href="@Url.Action("Browse", "Store", new { id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory, page = 1, itemPerPage = @Model.ItemPerPage, sort = 1})"><i class="m-icon-swapdown"></i></a>
        </div>   
        <div align="right" background="red">
            На странице:
            <div class="m-btn-group">
                <a class="m-btn dropdown-toggle mini" data-toggle="dropdown" href="#">
                    @Model.ItemPerPage <span class="caret"></span>
                </a>
                <ul class="m-dropdown-menu">
                    <li><a href="@Url.Action("Browse", new {id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory,  page = 1, itemPerPage = 5, sort = @ViewBag.sort})" >5</a></li>
                    <li><a href="@Url.Action("Browse", new {id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory,  page = 1, itemPerPage = 10, sort = @ViewBag.sort})" >10</a></li>
                    <li><a href="@Url.Action("Browse", new {id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory,  page = 1, itemPerPage = 20, sort = @ViewBag.sort})" >20</a></li>
                    <li><a href="@Url.Action("Browse", new {id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory, page = 1, itemPerPage = 50, sort = @ViewBag.sort})" >50</a></li>
                    <li><a href="@Url.Action("Browse", new {id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory,  page = 1, itemPerPage = 100, sort = @ViewBag.sort})" >100</a></li>
                </ul>
                @Html.PageLinks(Model.PageNo, Model.CountPage, x => Url.Action("Browse", new {id = @ViewBag.categoryId, isCategory = @ViewBag.IsCategory, page = x, itemPerPage = Model.ItemPerPage, sort = @ViewBag.sort}))
            </div>
        </div>
    </div>
    <ul id="album-list">
        @foreach (var product in Model.List)
        {
            <li>
                <a href="@Url.Action("Details", new { id = product.ProductId })">
                    <img height="100" width="130" alt="@product.Name" src="@(Path.Combine(product.ArtUrl, (new DirectoryInfo(Server.MapPath(product.ArtUrl))).GetFiles("*.jpg")[0].Name))"/>
                    <span>@product.Name</span>
                </a>
                <div class="display-field">@product.Price грн.</div>
            </li>
        }
    </ul>
    <div class="m-btn-group">
        @Html.PageLinks(Model.PageNo, Model.CountPage, x => Url.Action("Browse", new { id = @ViewBag.categoryId, page = x, itemPerPage = Model.ItemPerPage, sort = @ViewBag.sort }))
    </div>
</div>

MagicBoxShop/Views/Store/Details.cshtml
@model MagicBoxShop.Models.Product
@{
    ViewBag.Title = Model.Name;
}
<link href="@Url.Content("~/Content/gallery.css")" rel="stylesheet" 
      type="text/css" />
<script src="@Url.Content("~/Scripts/todo.js")" 
        type="text/javascript"></script>
<script type="text/javascript">
    todo.onload(function(){
        todo.gallery('gallery');
    });
</script>

<link href="@Url.Content("~/Content/Tabs.css")" rel="stylesheet" 
      type="text/css" />
<script src="@Url.Content("~/Scripts/Tabs.js")" 
        type="text/javascript"></script>
<h2>@Model.Name</h2>
<!-- Сами вкладки -->
<ul id="Tabs">
	<li id="TwoTab" class="Tab"><a href="#Two" onclick="Two(); return false;">Отзывы</a></li>
	<li id="OneTab" class="SelectedTab"><a href="#One" onclick="One(); return false;">Характеристики</a></li>
</ul>
<!-- Содержимое вкладок -->
<div id="Content">
	<!-- Первая -->
	<div id="One">
        @using (Html.BeginForm())
        {
            <ul id="detail-list">
                @foreach (var img in ViewBag.ListImg)
                {
                    <li>
                        <a title="@Model.Name" rel="gallery[myphoto]" href="@img"><img alt="@Model.Name" src="@img" height="150"> </a>    
                    </li>
                }
            </ul>

            <div id="album-details">
                <p>
                    <em>Цена:</em>
                    @String.Format("{0:F}", Model.Price)
                </p>
                <p>
                    <em>Описание:</em>
                    @Model.Description
                </p>

                @if (Model.Quantity > 0)
                {               
                 <div>
                    <input type="number" name="count" value="1" size="3" min="1" max="@Model.Quantity" />
                </div>
                    <div>
                        <input type="submit" value="Добавить в корзину" />
                    </div>
                }
                else
                {
                    <em>Товара нет в наличии</em>
                }
                <a href="javascript:history.go(-1)" class="mp-back">Назад</a>

            </div>
        }
    </div>
</div>
 
	<!-- Вторая -->
    <div id="Two" style="display: none;">
        <h3>Добавить свой комментарий </h3><em>(Комментарий появится на странице после модерации)</em>
        @{Html.RenderAction("Create", "Comment", new {id = Model.ProductId});}
        @{Html.RenderAction("Browse", "Comment", new {id = Model.ProductId});}
    </div>
</div>

MagicBoxShop/Views/Store/Index.cshtml
@model IEnumerable<MagicBoxShop.Models.Subcategory>
@{
    ViewBag.Title = "Товары";
}
<h3>Список категорий</h3>

<ul>
    @foreach (var ev in Model)
    {
        <li>@Html.ActionLink(ev.Name, "Browse", new { id = ev.SubcategoryId})</li>
    }
</ul>

MagicBoxShop/Views/Store/Menu.cshtml
@model IEnumerable<MagicBoxShop.Models.Category>

<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/icons.css")" />
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/component.css")" />
<!--[if gte IE 5.5]>
<script src="@Url.Content("~/Scripts/nav-h.js")" 
        type="text/javascript"></script>
<![endif]-->
<ul id="navmenu-v">
    @foreach (var category in Model)
    {
      if(category.Subcategories.Count > 0)
      {
          <li>
                @if (@Roles.IsUserInRole("Admin"))
                {
                    @Html.ActionLink(category.Name, "IndexConcrete", "StoreManager", new { id = category.CategoryId, isCategory = true }, null);
                }
                else
                {
                    @Html.ActionLink(category.Name, "Browse", "Store", new { id = category.CategoryId, isCategory = true }, null);
                }
             
                   <ul>
                       @foreach (var subcategory in category.Subcategories)
                       {
                           if(subcategory.Products.Count>0)
                           {
                            <li>
                            @if (@Roles.IsUserInRole("Admin"))
                                {
                                    @Html.ActionLink(subcategory.Name, "IndexConcrete", "StoreManager", new { id = subcategory.SubcategoryId, isCategory = false }, null);
                                }
                                else
                                {
                                    @Html.ActionLink(subcategory.Name, "Browse", "Store", new {  id = subcategory.SubcategoryId, isCategory = false  }, null);
                                }
                           </li>
                           }

                       }
                    </ul>
          </li>
      }
    }
    @if (@Roles.IsUserInRole("Admin"))
    {
        <li> @Html.ActionLink("Все товары", "Index", "StoreManager")</li>
        <li> @Html.ActionLink("Заказы", "Index", "Order")</li>
        <li> @Html.ActionLink("Категории", "Index", "Category")</li>
        <li> @Html.ActionLink("Подкатегории", "Index", "Subcategory")</li>
        <li> @Html.ActionLink("Отзывы", "Index", "Comment")</li>
    }
    
</ul>